# ONEngine AI Tree Backup Cleanup Script
# This script removes all .bak files generated by the Behavior Tree Editor.

$targetDir = Join-Path $PSScriptRoot "Assets/AITrees"

if (Test-Path $targetDir) {
    $bakFiles = Get-ChildItem -Path $targetDir -Filter "*.bak" -Recurse
    if ($bakFiles.Count -gt 0) {
        Write-Host "Found $($bakFiles.Count) backup files. Cleaning up..." -ForegroundColor Cyan
        $bakFiles | Remove-Item -Force
        Write-Host "Cleanup completed successfully." -ForegroundColor Green
    } else {
        Write-Host "No backup files found in $targetDir." -ForegroundColor Yellow
    }
} else {
    Write-Warning "Target directory not found: $targetDir"
}
